[package]
name = "blind-watermark"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1"
faer = "0.23"
image = "0.25"
num = "0.4"
bitvec = "1.0"
derive_builder = "0.20"

[profile.dev.package.faer]
opt-level = 3


[dev-dependencies]
approx = "0.5"
